# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer1.org0.bjca.com:
    container_name: orderer1.org0.bjca.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts:/var/hyperledger/orderer/configtx
        - ../crypto-config-20210329/orderer1.org0/msp:/var/hyperledger/orderer/msp
        - ../crypto-config-20210329/orderer1.org0/tls:/var/hyperledger/orderer/tls
        - orderer1.org0.bjca.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.bjca.com:
    container_name: peer0.org1.bjca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.bjca.com
      - CORE_PEER_ADDRESS=peer0.org1.bjca.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.bjca.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.bjca.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bjca.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config-20210329/peer0.org1/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config-20210329/peer0.org1/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.bjca.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.bjca.com:
    container_name: peer1.org1.bjca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.bjca.com
      - CORE_PEER_ADDRESS=peer1.org1.bjca.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.bjca.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.bjca.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bjca.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config-20210329/peer1.org1/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config-20210329/peer1.org1/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.bjca.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.bjca.com:
    container_name: peer0.org2.bjca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.bjca.com
      - CORE_PEER_ADDRESS=peer0.org2.bjca.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.bjca.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.bjca.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.bjca.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config-20210329/peer0.org2/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config-20210329/peer0.org2/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.bjca.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.bjca.com:
    container_name: peer1.org2.bjca.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.bjca.com
      - CORE_PEER_ADDRESS=peer1.org2.bjca.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.bjca.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.bjca.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.bjca.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config-20210329/peer1.org2/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config-20210329/peer1.org2/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.bjca.com:/var/hyperledger/production
    ports:
      - 10051:10051
