# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.org0.bjca.com:
  peer0.org1.bjca.com:
  peer1.org1.bjca.com:
  peer0.org2.bjca.com:
  peer1.org2.bjca.com:

networks:
  bjca:

services:

  orderer1.org0.bjca.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.org0.bjca.com
    container_name: orderer1.org0.bjca.com
    networks:
      - bjca

  peer0.org1.bjca.com:
    container_name: peer0.org1.bjca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.bjca.com
    networks:
      - bjca

  peer1.org1.bjca.com:
    container_name: peer1.org1.bjca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.bjca.com
    networks:
      - bjca

  peer0.org2.bjca.com:
    container_name: peer0.org2.bjca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.bjca.com
    networks:
      - bjca

  peer1.org2.bjca.com:
    container_name: peer1.org2.bjca.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.bjca.com
    networks:
      - bjca

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.bjca.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peer0.org1/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peer0.org1/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peer0.org1/tls/ica.cert.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/admin.org1/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config-20210329:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.org0.bjca.com
      - peer0.org1.bjca.com
      - peer1.org1.bjca.com
      - peer0.org2.bjca.com
      - peer1.org2.bjca.com
    networks:
      - bjca
