# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.org0.bjca.com:
  orderer3.org0.bjca.com:

networks:
  bjca:

services:

  orderer2.org0.bjca.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.org0.bjca.com
    networks:
    - bjca
    volumes:
        - ./channel-artifacts:/var/hyperledger/orderer/configtx
        - ./crypto-config-20210329/orderer2.org0/msp:/var/hyperledger/orderer/msp
        - ./crypto-config-20210329/orderer2.org0/tls/:/var/hyperledger/orderer/tls
        - orderer2.org0.bjca.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.org0.bjca.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.org0.bjca.com
    networks:
    - bjca
    volumes:
        - ./channel-artifacts:/var/hyperledger/orderer/configtx
        - ./crypto-config-20210329/orderer3.org0/msp:/var/hyperledger/orderer/msp
        - ./crypto-config-20210329/orderer3.org0/tls/:/var/hyperledger/orderer/tls
        - orderer3.org0.bjca.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

